#cloud-config
runcmd:
  - [sudo, yum, update, -y]
  - [sudo, amazon-linux-extras, install, docker, -y]
  - [sudo, service, docker, start]
  - [sudo, usermod, -a, -G, docker, ec2-user]
  - 'sudo curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose'
  - [sudo, chmod, +x, /usr/local/bin/docker-compose]
